//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatbotDialogGenerator.Configuration {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class UnitTests : global::System.Configuration.ApplicationSettingsBase {
        
        private static UnitTests defaultInstance = ((UnitTests)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UnitTests())));
        
        public static UnitTests Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tests\\")]
        public string UnitTestsFolderPath {
            get {
                return ((string)(this["UnitTestsFolderPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>System.Threading.Tasks</string>
  <string>Autofac</string>
  <string>Core.Dialogs</string>
  <string>Core.Extensions</string>
  <string>Core.Invokers</string>
  <string>Objectivity.Bot.Tests.Stories.Recorder</string>
  <string>Objectivity.Bot.Tests.Stories.Xunit</string>
  <string>Tests.Common.DI</string>
  <string>Xunit</string>
  <string>Objectivity.Bot.Tests.Stories.Xunit.Extensions</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UnitTestsUsings {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UnitTestsUsings"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DialogUnitTestBase")]
        public string UnitTestBaseClass {
            get {
                return ((string)(this["UnitTestBaseClass"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("result => result.DialogResultType == DialogResultType.AskForAnotherQuestion")]
        public string UnitTestDonePredicate {
            get {
                return ((string)(this["UnitTestDonePredicate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Target.Project.UnitTests")]
        public string UnitTestsProjectName {
            get {
                return ((string)(this["UnitTestsProjectName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Target.Project.UnitTests")]
        public string UnitTestNamespace {
            get {
                return ((string)(this["UnitTestNamespace"]));
            }
        }
    }
}
