//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatbotDialogGenerator.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatbotDialogGenerator.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///namespace Target.Project.UnitTests
        ///{
        ///    using Autofac;
        ///    using Core.Dialogs;
        ///    using Core.Extensions;
        ///    using Core.Invokers;
        ///    using Objectivity.Bot.Tests.Stories.Recorder;
        ///    using Objectivity.Bot.Tests.Stories.Xunit;
        ///    using Objectivity.Bot [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExpectedDialogTest {
            get {
                return ResourceManager.GetString("ExpectedDialogTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///namespace TestNamespace
        ///{
        ///    using Core.Dialogs;
        ///    using Core.Extensions;
        ///    using Core.Invokers;
        ///
        ///    [Export(typeof(ITestDialog))]
        ///    public class TestDialog : ITestDialog
        ///    {
        ///        private readonly IDialogInvoker dialogInvoker;
        ///        priv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExpectedDialogWithDependencies {
            get {
                return ResourceManager.GetString("ExpectedDialogWithDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///namespace TestNamespace
        ///{
        ///    using Core.Dialogs;
        ///    using Core.Extensions;
        ///    using Core.Invokers;
        ///
        ///    [Export(typeof(ITestDialog))]
        ///    public class TestDialog : ITestDialog
        ///    {
        ///        public async Task StartAsync(IDialogContext context)
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExpectedDialogWithoutDependencies {
            get {
                return ResourceManager.GetString("ExpectedDialogWithoutDependencies", resourceCulture);
            }
        }
    }
}
